import re

content = """import React, { useState, useEffect } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/lib/supabase';
import { Trophy, Target, Clock, Users, Star, CheckCircle2, Loader2, Sparkles, Flame, DollarSign, Brain } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { toast } from 'sonner';

export default function CoffeeChallengesPage() {
  const { profile } = useAuth();
  const [activeCampaigns, setActiveCampaigns] = useState<any[]>([]);
  const [participations, setParticipations] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    if (profile?.id) {
      fetchData();
    }
  }, [profile?.id]);

  const fetchData = async () => {
    try {
      setIsLoading(true);
      // Fetch all active AI campaigns
      const { data: campaigns } = await supabase
        .from('ai_generated_campaigns')
        .select('*')
        .eq('status', 'active');
        
      // Fetch user's participations
      const { data: userParts } = await supabase
        .from('ai_campaign_participants')
        .select('*')
        .eq('customer_id', profile!.id);
        
      setActiveCampaigns(campaigns || []);
      setParticipations(userParts || []);
    } catch (err) {
      console.error('Error fetching campaigns:', err);
      toast.error('Failed to load active campaigns.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleJoin = async (campaign: any) => {
    try {
      const targetCount = 3; // Defaulting for simple gamification if rules not set
      
      const { data, error } = await supabase
        .from('ai_campaign_participants')
        .insert({
          campaign_id: campaign.id,
          customer_id: profile!.id,
          current_progress: 0,
          target_count: targetCount,
          completed: false
        }).select().single();
        
      if (error) throw error;
      
      toast.success(`You joined: ${campaign.title}!`);
      fetchData();
    } catch (err) {
      toast.error('Could not join campaign');
    }
  };

  if (isLoading) {
    return (
      <div className="p-4 md:p-8 max-w-5xl mx-auto flex items-center justify-center min-h-[400px]">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  const getIconForType = (type: string) => {
    switch (type?.toLowerCase()) {
      case 'win-back': return <Clock className="w-6 h-6 text-warning" />;
      case 'product_discovery': return <Target className="w-6 h-6 text-green-500" />;
      case 'loyalty': return <Trophy className="w-6 h-6 text-primary" />;
      case 'promotion': return <DollarSign className="w-6 h-6 text-purple-500" />;
      default: return <Sparkles className="w-6 h-6 text-primary" />;
    }
  };

  const calculateRemainingDays = (endDateStr: string) => {
    if (!endDateStr) return 'Unknown';
    const end = new Date(endDateStr).getTime();
    const now = new Date().getTime();
    const diff = end - now;
    if (diff < 0) return 'Expired';
    const days = Math.ceil(diff / (1000 * 3600 * 24));
    return days === 0 ? 'Ending Today' : `${days} Days Left`;
  };

  const renderReward = (details: any) => {
    if (!details) return 'Exclusive Reward';
    if (details.type === 'points') return `${details.value} Bonus Points`;
    if (details.type === 'discount') return `${details.value}% Off`;
    if (details.type === 'upgrade') return `Free Size Upgrade`;
    return details.description || 'Special Reward';
  };

  return (
    <div className="p-4 md:p-8 max-w-5xl mx-auto space-y-8 animate-in fade-in-0 pb-20">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-2">
        <div className="flex items-center gap-3">
          <Brain className="w-8 h-8 text-primary" />
          <h1 className="text-3xl font-heading font-semibold text-foreground">Active Campaigns</h1>
        </div>
      </div>
      <p className="text-muted-foreground text-balance">
        Curated challenges and offers automatically generated by the Coffee OS AI Growth Engine specifically for you.
      </p>

      <div className="mt-8">
        {activeCampaigns.length === 0 ? (
          <div className="glass p-12 rounded-2xl border border-border flex flex-col items-center justify-center text-center">
             <Trophy className="w-12 h-12 text-muted-foreground mb-4 opacity-50" />
             <h3 className="text-lg font-bold">No Active Campaigns</h3>
             <p className="text-muted-foreground text-sm max-w-sm mt-2">The AI Growth Engine hasn't released any new campaigns yet. Check back soon!</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6">
            <AnimatePresence>
              {activeCampaigns.map((campaign, idx) => {
                const part = participations.find(p => p.campaign_id === campaign.id);
                const isJoined = !!part;
                const isCompleted = part?.completed;
                const progress = part?.current_progress || 0;
                const target = part?.target_count || 3;
                
                return (
                  <motion.div 
                    key={campaign.id}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: idx * 0.1 }}
                    className="glass rounded-2xl p-6 border border-border shadow-sm flex flex-col relative overflow-hidden bg-gradient-to-br from-primary/5 to-transparent"
                  >
                    {isCompleted && (
                      <div className="absolute inset-0 bg-background/80 backdrop-blur-[2px] z-10 flex flex-col items-center justify-center">
                        <CheckCircle2 className="w-16 h-16 text-primary mb-2 shadow-sm bg-background rounded-full" />
                        <span className="font-bold text-lg text-primary bg-background px-3 py-1 rounded-full border border-border shadow-sm">Completed!</span>
                      </div>
                    )}
                    
                    <div className="flex justify-between items-start mb-4">
                      <div className="w-12 h-12 rounded-xl bg-background border border-border flex items-center justify-center shadow-sm text-primary">
                        {getIconForType(campaign.campaign_type)}
                      </div>
                      <div className="bg-background border border-border text-foreground text-[10px] font-bold uppercase tracking-wider px-2 py-1 rounded shadow-sm">
                        {calculateRemainingDays(campaign.recommended_end_date || campaign.actual_end_date)}
                      </div>
                    </div>
                    
                    <h3 className="text-lg font-bold mb-1 leading-tight">{campaign.title}</h3>
                    <p className="text-sm text-muted-foreground mb-6 flex-1">{campaign.description}</p>
                    
                    {isJoined ? (
                      <div className="bg-background/50 rounded-lg p-4 border border-border mb-4 shadow-inner">
                        <div className="flex justify-between text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-2">
                          <span>Progress</span>
                          <span className="text-foreground">{progress} / {target}</span>
                        </div>
                        <Progress value={Math.min((progress / target) * 100, 100)} className="h-2 bg-secondary" />
                      </div>
                    ) : (
                      <Button onClick={() => handleJoin(campaign)} className="w-full mb-4 shadow-sm font-semibold group">
                        Join Campaign <ArrowRight className="w-4 h-4 ml-2 group-hover:translate-x-1 transition-transform" />
                      </Button>
                    )}
                    
                    <div className="flex justify-between items-center bg-secondary/30 p-3 rounded-lg border border-border/50">
                       <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Reward</span>
                       <div className="flex items-center gap-1.5 text-sm font-bold text-primary">
                         <Star className="w-4 h-4" /> {renderReward(campaign.reward_details)}
                       </div>
                    </div>
                  </motion.div>
                );
              })}
            </AnimatePresence>
          </div>
        )}
      </div>
    </div>
  );
}
"""

with open('/workspace/app-cvq4redfdog1/src/pages/account/CoffeeChallengesPage.tsx', 'w') as f:
    f.write(content)
